# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20160908_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
    ]
