# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_address_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='terms_accepted',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='terms accepted'),
        ),
    ]
